SUPABASE_URL = "https://ogvmogrdawdoyrzyqrrr.supabase.co"
SUPABASE_KEY = "sb_publishable_wMprpNuUMNkejnq4tt3GnA_JKWtbHeA"
GROQ_API_KEY = "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"
        